#!/bin/bash
cd ~/.vim/bundle
git clone https://github.com/MattesGroeger/vim-bookmarks.git
git clone https://github.com/SirVer/ultisnips.git
git clone https://github.com/adoy/vim-php-refactoring-toolbox.git
git clone https://github.com/airblade/vim-gitgutter.git
git clone https://github.com/bling/vim-airline.git
git clone https://github.com/blueyed/vim-diminactive
git clone https://github.com/bogado/file-line.git
git clone https://github.com/chase/vim-ansible-yaml
git clone https://github.com/christoomey/vim-tmux-navigator.git
git clone https://github.com/derekprior/vim-trimmer.git
git clone https://github.com/duggiefresh/vim-easydir.git
git clone https://github.com/easymotion/vim-easymotion.git
git clone https://github.com/ekalinin/Dockerfile.vim.git
git clone https://github.com/elzr/vim-json
git clone https://github.com/farseer90718/vim-taskwarrior
git clone https://github.com/godlygeek/tabular.git
git clone https://github.com/gregsexton/gitv.git
git clone https://github.com/henrik/vim-qargs.git
git clone https://github.com/honza/vim-snippets.git
git clone https://github.com/kchmck/vim-coffee-script.git
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/lifepillar/vim-solarized8.git ~/.vim/pack/themes/opt/solarized8
git clone https://github.com/majutsushi/tagbar.git
git clone https://github.com/mattn/gist-vim.git
git clone https://github.com/mattn/webapi-vim.git
git clone https://github.com/mhinz/vim-startify.git
git clone https://github.com/moll/vim-node.git
git clone https://github.com/mtscout6/syntastic-local-eslint.vim.git
git clone https://github.com/pangloss/vim-javascript
git clone https://github.com/pearofducks/ansible-vim.git
git clone https://github.com/rking/ag.vim.git
git clone https://github.com/robbles/logstash.vim.git
git clone https://github.com/rodjek/vim-puppet.git
git clone https://github.com/scrooloose/nerdcommenter.git
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/scrooloose/syntastic.git
git clone https://github.com/sjl/gundo.vim.git
git clone https://github.com/terryma/vim-multiple-cursors.git
git clone https://github.com/thaerkh/vim-workspace.git
git clone https://github.com/tpope/vim-abolish.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/tpope/vim-surround.git
git clone https://github.com/vitalk/vim-simple-todo
git clone https://github.com/yssl/QFEnter.git
